# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afd0763f02f8a1160d51d3e9adb714905e3e60d90564d9ba3b07248f1970fdad77e24c1614bc42a815cfd3e339be4db2a5d745eecbd40a38578d929fe958b2c0

test:
  secret_key_base: a9b644344c75389e80368b34730767c307f38da89eb87aa867da0a3c26167214ee77747e2d34bcdbc1e210b07e3ed62131b38b13f20a7760744d7f2c90c365a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
